ttc:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'C:\Users\shoaib\ttc-pipeline\ttc.duckdb'
      threads: 2
      settings:
        memory_limit: '4GB'
        preserve_insertion_order: false
    airflow:
      type: duckdb
      path: /opt/airflow/ttc-project/ttc.duckdb
      threads: 2